### ISSUE TITLE
LineageOS 14.1 status

### ISSUE THREAD

**Issue by cmorlok** [aquaris-dev/android_device_bq_gohan#2]
Working:
* Sensors
* Fingerprint sensor
* GPS 
* Bluetooth
* Camera

Not working:
* Speaker (workaround available: replace audio.primary.msm8952.so by stock lib)
* Serial number is wrong

Untested:
* Mobile data
* Calls
* Headset

**Comment by cyclon1978** [comment]
I tested the current version.

Additional things working:

- Mobile Data
- Calls (incoming, outgoing)

Overall very stable, very battery friendly.

**Comment by manuelmagix** [comment]
Reemplazados librerias audio de 7.1.1. stock a lianage, y funcionando  altavoz!!!!!
Gracias.

**Comment by Kra1o5** [comment]
We are working in a best way to fix that.

**Comment by cyclon1978** [comment]
Camera works partially if you use these files from stock. 

- Preview: always wrong colors, more or less artifacts depending on resolution
- taking Photos: Result is perfect (colors good, no artifacts)
- taking Videos: Result is mixed depending on resolution (colors always good, but more or less artifacts)

/system/etc/camera/camera_config.xml
/system/etc/camera/imx219_cmb104_chromatix.xml
/system/etc/camera/imx219_d8n03d_chromatix.xml
/system/etc/camera/imx298_chromatix.xml
/system/etc/camera/imx298_cmb087qr_chromatix.xml

/system/etc/firmware/a225p5_pm4.fw
/system/etc/firmware/a225_pfp.fw
/system/etc/firmware/a225_pm4.fw
/system/etc/firmware/a300_pfp.fw
/system/etc/firmware/a300_pm4.fw
/system/etc/firmware/a330_pfp.fw
/system/etc/firmware/a330_pm4.fw
/system/etc/firmware/a420_pfp.fw
/system/etc/firmware/a420_pm4.fw
/system/etc/firmware/cpp_firmware_v1_5_1.fw
/system/etc/firmware/ice40.bin
/system/etc/firmware/leia_pfp_470.fw
/system/etc/firmware/leia_pm4_470.fw
/system/etc/firmware/nvm_tlv_1.3.bin
/system/etc/firmware/nvm_tlv_2.1.bin
/system/etc/firmware/nvm_tlv_3.0.bin
/system/etc/firmware/nvm_tlv_3.2.bin
/system/etc/firmware/nvm_tlv.bin
/system/etc/firmware/rampatch_tlv_1.3.tlv
/system/etc/firmware/rampatch_tlv_2.1.tlv
/system/etc/firmware/rampatch_tlv_3.0.tlv
/system/etc/firmware/rampatch_tlv_3.2.tlv
/system/etc/firmware/rampatch_tlv.img
/system/etc/firmware/synaptics_firmware_booyi.img

some of these files might not be required, but at least some from both groups (firmware and camera folder) are required.

**Comment by cyclon1978** [comment]
Camera works perfect if you use these files from stock. 

/system/etc/camera/camera_config.xml
/system/etc/camera/imx219_cmb104_chromatix.xml
/system/etc/camera/imx219_d8n03d_chromatix.xml
/system/etc/camera/imx298_chromatix.xml
/system/etc/camera/imx298_cmb087qr_chromatix.xml

/system/etc/firmware/a225p5_pm4.fw
/system/etc/firmware/a225_pfp.fw
/system/etc/firmware/a225_pm4.fw
/system/etc/firmware/a300_pfp.fw
/system/etc/firmware/a300_pm4.fw
/system/etc/firmware/a330_pfp.fw
/system/etc/firmware/a330_pm4.fw
/system/etc/firmware/a420_pfp.fw
/system/etc/firmware/a420_pm4.fw
/system/etc/firmware/cpp_firmware_v1_5_1.fw
/system/etc/firmware/ice40.bin
/system/etc/firmware/leia_pfp_470.fw
/system/etc/firmware/leia_pm4_470.fw
/system/etc/firmware/nvm_tlv_1.3.bin
/system/etc/firmware/nvm_tlv_2.1.bin
/system/etc/firmware/nvm_tlv_3.0.bin
/system/etc/firmware/nvm_tlv_3.2.bin
/system/etc/firmware/nvm_tlv.bin
/system/etc/firmware/rampatch_tlv_1.3.tlv
/system/etc/firmware/rampatch_tlv_2.1.tlv
/system/etc/firmware/rampatch_tlv_3.0.tlv
/system/etc/firmware/rampatch_tlv_3.2.tlv
/system/etc/firmware/rampatch_tlv.img
/system/etc/firmware/synaptics_firmware_booyi.img

/system/lib/hw/gralloc.msm8952.so

**Comment by manuelmagix** [comment]
Bravo cyclon!!!!
camara bq work fine.

**Comment by cyclon1978** [comment]
Why are we using a prebuild/stock /system/lib/hw/camera.msm8952.so ?

Should be compilable from source, using the caf sources: https://source.codeaurora.org/quic/la/platform/hardware/qcom/camera/tree/QCamera2/Android.mk?h=LA.BR.1.3.6.c2_rb2.12

Good idea? Has anyone already tried?

**Comment by cmorlok** [comment]
BQ's camera hal is not purely CAF but contains proprietary extensions (beautyshot for example). You'll loose those features if you use the open source hal, that's why users requested to switch to the closed source hal on piccolo. We won't use the open source hal unless there is a good reason for (or anyone patched the open source hal to use BQ's extensions)

**Comment by cyclon1978** [comment]
Sooo... I tried it anyway and now i use caf camera.msm8952.so and some other libs. The ones from lineageos didnt work, i took the ones from bq tag (from stock build.prop), but newer versions should work too.

Now i tested the stock bq cam app with my selfbuild aosp-caf camera.msm8952.so and i see no difference in quality and all features in bq app are working.

So i wonder if i am missing something - cant find a beautyshot mode but i think that was no option in stock rom too.

Can anyone point out how this feature was visible in bq camera app?

**Comment by cmorlok** [comment]
Could you please push the change(s) to gerrit? I will have a look. And
could you please send me the list of files required to install the stock
camera? We will provide a flashable zip (as we did for other devices).

**Comment by danielotero** [comment]
The only thing I see as beauty mode in the stock camera is the slider that
can be seen in the attached image.

https://cloud.githubusercontent.com/assets/9847857/25752424/7c68ae6c-31b8-11e7-911a-50ff91540550.png

It only appears in the front camera when the app detects a face. It softens
the skin, but I personally don't find it a killer feature.

Hope it helps and thank you all for your work.


PS: Sorry about the lastest message, I thought that GitHub handle the email responses better.

**Comment by 0xCHERRY** [comment]
I build and installed `14.1` for gohan using the following roomservice.xml manifest

```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" remote="github"/>
  <project name="LineageOS/android_external_sony_boringssl-compat" path="external/sony/boringssl-compat" remote="github" />
  <project name="LineageOS/android_external_stlport" path="external/stlport" remote="github" />
  <project name="aquaris-dev/android_device_bq_gohan" path="device/bq/gohan" remote="github" revision="cm-14.1" />
  <project name="aquaris-dev/android_kernel_bq_msm8976" path="kernel/bq/msm8976" remote="github" revision="cm-14.1" />
  <project name="aquaris-dev/proprietary_vendor_bq" path="vendor/bq" remote="github" revision="cm-14.1" />
</manifest>
```

Everything is working, with exception of microphone/speaker support.

**Comment by 0xCHERRY** [comment]
Follow the official manual for [paella](https://wiki.lineageos.org/devices/paella/build) in order to **prepare your system**.

Download the source code

```sh
$ cd android/lineage
$ repo sync
```

Prepare the device-specific code

```sh
$ source build/envsetup.sh
$ breakfast gohan
```

Update the installation manifest

```sh
$ vi android/system/.repo/local_manifests/roomservice.xml
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" remote="github"/>
  <project name="LineageOS/android_external_sony_boringssl-compat" path="external/sony/boringssl-compat" remote="github" />
  <project name="LineageOS/android_external_stlport" path="external/stlport" remote="github" />
  <project name="aquaris-dev/android_device_bq_gohan" path="device/bq/gohan" remote="github" revision="cm-14.1" />
  <project name="aquaris-dev/android_kernel_bq_msm8976" path="kernel/bq/msm8976" remote="github" revision="cm-14.1" />
  <project name="aquaris-dev/proprietary_vendor_bq" path="vendor/bq" remote="github" revision="cm-14.1" />
</manifest>
```

Resync and download the device-specific code

```sh
$ repo sync
```

Continue building cm-14.1 for gohan

```sh
$ brunch gohan
```

With exception camera, microphone/speaker support, everything is working (as mentioned above).

**Comment by 0xCHERRY** [comment]
Follow the official manual for [paella](https://wiki.lineageos.org/devices/paella/build) in order to **prepare your system**.

Download the source code

```sh
$ cd android/lineage
$ repo sync
```

Prepare the device-specific code

```sh
$ source build/envsetup.sh
$ breakfast gohan
```

Update the installation manifest

```sh
$ vi .repo/local_manifests/roomservice.xml
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" remote="github"/>
  <project name="LineageOS/android_external_sony_boringssl-compat" path="external/sony/boringssl-compat" remote="github" />
  <project name="LineageOS/android_external_stlport" path="external/stlport" remote="github" />
  <project name="aquaris-dev/android_device_bq_gohan" path="device/bq/gohan" remote="github" revision="cm-14.1" />
  <project name="aquaris-dev/android_kernel_bq_msm8976" path="kernel/bq/msm8976" remote="github" revision="cm-14.1" />
  <project name="aquaris-dev/proprietary_vendor_bq" path="vendor/bq" remote="github" revision="cm-14.1" />
</manifest>
```

Resync and download the device-specific code

```sh
$ repo sync
```

Continue building cm-14.1 for gohan

```sh
$ brunch gohan
```

With exception camera, microphone/speaker support, everything is working (as mentioned above).

**Comment by cherryland** [comment]
Follow the official manual for [paella](https://wiki.lineageos.org/devices/paella/build) in order to **prepare your system**.

Download the source code

```sh
$ cd android/lineage
$ repo sync
```

Prepare the device-specific code

```sh
$ source build/envsetup.sh
$ breakfast gohan
```

Update the installation manifest

```sh
$ vi .repo/local_manifests/roomservice.xml
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" remote="github"/>
  <project name="LineageOS/android_external_sony_boringssl-compat" path="external/sony/boringssl-compat" remote="github" />
  <project name="LineageOS/android_external_stlport" path="external/stlport" remote="github" />
  <project name="aquaris-dev/android_device_bq_gohan" path="device/bq/gohan" remote="github" revision="cm-14.1" />
  <project name="aquaris-dev/android_kernel_bq_msm8976" path="kernel/bq/msm8976" remote="github" revision="cm-14.1" />
  <project name="aquaris-dev/proprietary_vendor_bq" path="vendor/bq" remote="github" revision="cm-14.1" />
</manifest>
```

Resync and download the device-specific code

```sh
$ repo sync
```

Continue building cm-14.1 for gohan

```sh
$ brunch gohan
```

With exception of camera, microphone/speaker support, everything is working (as mentioned above).

**Comment by cmorlok** [comment]
Bluetooth, Camera and FM radio is fixed, changes will be merged soon. 

We are working on the speaker issue.

**Comment by cyclon1978** [comment]
nfc works but does not support "extended length" feature. This is not a kernel-driver Issue. 

Stock rom supports extended length.

Looks like a common LOS problem but needs looking into it...
NativeNfcManager.java

```
   @Override
    public boolean getExtendedLengthApdusSupported() {
        // TODO check BCM support
        return false;
    }

   @Override
    public int getMaxTransceiveLength(int technology) {
        switch (technology) {
            case (TagTechnology.NFC_A):
            case (TagTechnology.MIFARE_CLASSIC):
            case (TagTechnology.MIFARE_ULTRALIGHT):
                return 253; // PN544 RF buffer = 255 bytes, subtract two for CRC
            case (TagTechnology.NFC_B):
                /////////////////////////////////////////////////////////////////
                // Broadcom: Since BCM2079x supports this, set NfcB max size.
                //return 0; // PN544 does not support transceive of raw NfcB
                return 253; // PN544 does not support transceive of raw NfcB
            case (TagTechnology.NFC_V):
                return 253; // PN544 RF buffer = 255 bytes, subtract two for CRC
            case (TagTechnology.ISO_DEP):
                /* The maximum length of a normal IsoDep frame consists of:
                 * CLA, INS, P1, P2, LC, LE + 255 payload bytes = 261 bytes
                 * such a frame is supported. Extended length frames however
                 * are not supported.
                 */
                return 261; // Will be automatically split in two frames on the RF layer
            case (TagTechnology.NFC_F):
                return 252; // PN544 RF buffer = 255 bytes, subtract one for SoD, two for CRC
            default:
                return 0;
        }
}
```
We need 2462 in length and a true instead of false...

**Comment by cherryland** [comment]
@cmorlok may you push the bluetooth changes into the branch? Awaiting your changes so I can at least use my bluetooth headset desu

**Comment by cmorlok** [comment]
@0xCHERRY: the Bluetooth fix has been merged last night:
https://review.lineageos.org/#/c/170843/
https://github.com/LineageOS/android_device_bq_gohan/commit/3016bc3042131c5dc838d67eeda2d090eb6f0f42

**Comment by manuelmagix** [comment]
Camera fc, when storage SD (for photo, for video  no fc).  in RC  20170516

**Comment by cherryland** [comment]
any updates on this?

**Comment by stucki** [comment]
The bq Aquaris X5 Plus is now officially supported by LineageOS via this team. See http://aquaris-dev.org/blog/2017/09/27/device-status.html for details.

If you still notice any problems, please open a new ticket (1 ticket per problem).
