### ISSUE TITLE
capacitive buttons do not vibrate

### ISSUE THREAD

**Issue by sknzl** [aquaris-dev/android_device_bq_gohan#8]
In newly installed LineageOS the capacitive buttons do not vibrate. The haptic feedback seems not to be working in general (also no vibration when double tap to wake is used). In Sound -> Other sounds the "Vibrate on tap" option is already checked.

**Comment by medmex** [comment]
I have the same problem.
Installed "Button Mapper" and problem solved.
I think this is something easy to solve in a future release of LineageOS as a third party app can manage that.

**Comment by cmorlok** [comment]
If you tell us how your configuration in "Button Mapper" looks like, it
should be easy to adapt this in lineage.

**Comment by medmex** [comment]
The app permits that you add vibration to certain buttons, as the home, back, recent apps and volume keys.
I don't know for sure how it is done, but you don't need to have root access for the app to do that. I dont't have my phone rooted.

**Comment by medmex** [comment]
I saw that a fix is coming out in next update.
Thanks!

**Comment by Kra1o5** [comment]
Yes @medmex, 
Should be fixed here: https://github.com/LineageOS/android_device_bq_gohan/commit/88e0bfb795144b30ea4dd0e83c7b8706e5d71e93 and included in next build.

I will wait your feedback before close this issue.

Regards,

**Comment by medmex** [comment]
It's fixed! 👍 
Thanks a lot.

**Comment by eloimuns** [comment]
Nice!
Let's close this.

**Comment by medmex** [comment]
Be my guest!
